name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyautogui keyboard pyinstaller

      - name: Build EXE
        run: pyinstaller --noconsole --onefile autokey.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: AutoKeyPress
          path: dist/autokey.exe
